### ISSUE TITLE
When installing lru-cache…, it corrupts my project (new configuration files, new lines in package.json)

### ISSUE THREAD

**Issue by mickaeltr** [doublesharp/lru-cache-for-clusters-as-promised#1]
Hello,

When I install my project, lru-cache-for-clusters-as-promised (~1.5.6) sometimes:

1. Adds new configuration files in my project:

- .depcheckrc
- .eslintignore
- .eslintrc

2. Adds new lines in my package.json

<img width="719" alt="screen shot 2017-01-27 at 09 55 57" src="https://cloud.githubusercontent.com/assets/378910/22365987/a27d7ece-e47a-11e6-8e88-526caecc9032.png">
<img width="133" alt="screen shot 2017-01-27 at 09 56 11" src="https://cloud.githubusercontent.com/assets/378910/22365994/ab8b7ce6-e47a-11e6-8e15-8d9d51691a9a.png">

3. Overwrites my Git hooks

It looks like itit comes from the developer-tools package: https://github.com/doublesharp/node-developer-tools

Do you know how I can prevent that?

Thanks

**Comment by doublesharp** [comment]
Sorry, that is pretty frustrating. I was using `developer-tools` to set up a dev environment specifically for this module, but it seems to be leaking sometimes. FWIW, this is one of the downsides I have found to using `npm` in general (executing scripts without permission) and have been switch my projects over to use `yarn`.

I'll see if I can get this switched over today so that it doesn't cause any more issues. Apologies again!

**Comment by doublesharp** [comment]
Ugh, this is actually because the `npm-shrinkwrap.json` didn't update after I accidentally included `developer-tools` in `dependencies` vs `devDependencies`... so it was my fault :(

Almost done converting to `yarn` and will publish shortly.

**Comment by doublesharp** [comment]
This should now be fixed in ba6373cfd1862d1c4290395940e2c9e2698b2aab v1.5.7

**Comment by mickaeltr** [comment]
Thanks @doublesharp
